/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Mata
 */
public class CrearReserva extends javax.swing.JFrame {

    String idSala;
    
    public CrearReserva(String pidSala) {
        this.idSala = pidSala;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label1.setText("Participantes");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 40, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 109, 78, 33));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 78, 36));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 109, 86, 33));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 160, 86, 34));

        jButton1.setText("Registrar Participante");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 214, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 56, 387, 199));

        label2.setText("Nombre");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, -1, -1));

        label3.setText("Primer Apellido");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        label4.setText("Correo");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        label5.setText("Segundo Apellido");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    // End of variables declaration//GEN-END:variables
}
